language: python

python:
    - 2.7
    - 3.2
    - 3.4

before_install:
    - uname -a
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - pip install --upgrade pip setuptools
    - pip install coveralls 
    - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy Cython scipy

# command to install dependencies
install:
    - "python setup.py install --with-f90mc"

# command to run tests
script: 
    - nosetests --with-coverage --cover-package=qutip qutip

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
          coveralls;
      fi #2017-08-27 19:26:53 modified at 0 #2017-08-27 19:26:57 modified at 1 #2017-08-27 19:27:02 modified at 2 #2017-08-27 19:27:06 modified at 3