language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - uname -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install --upgrade pip setuptools 
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy Cython scipy

# command to install dependencies
install:
  - "python setup.py install --with-f90mc"

# command to run tests
script: nosetests qutip
 #2017-08-27 19:50:31 modified at 0 #2017-08-27 19:50:35 modified at 1 #2017-08-27 19:50:40 modified at 2 #2017-08-27 19:50:44 modified at 3