sudo: false
language: python

python:
    - 2.7
    - 3.5
matrix:
    include:
        - python: 3.5
          env: CC=clang CXX=clang++

addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran


# command to install dependencies
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose cython
    - source activate test-environment
    - pip install coverage coveralls
    - python setup.py install --with-f90mc

# command to run tests
script: 
    - nosetests --with-coverage --cover-package=qutip qutip

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]] && [[ $CC == 'gcc' ]]; then
          coveralls;
      fi

 #2017-08-27 18:42:32 modified at 0 #2017-08-27 18:42:37 modified at 1